# Generated by Django 2.1.7 on 2019-03-21 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('week1task', models.TextField()),
                ('leaderforWeek', models.CharField(choices=[('Week1', 'Week 1'), ('Week2', 'Week 2'), ('Week3', 'Week 3'), ('Week4', 'Week 4'), ('Week5', 'Week 5'), ('Week6', 'Week 6')], max_length=50)),
            ],
        ),
    ]
